Amogus2009/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('custom_admin/', include('custom_admin.urls')),
    path("", include("user.urls")),
]

user/urls.py
from django.urls import path
from . import views
from .views import register, login

app_name = "user"
urlpatterns = [
    path("", views.index, name='index'),
    path("product/list/", views.get_list_product, name='product_list'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path("logout/", views.logout, name='logout'),
    path("error/", views.error, name='error')
]

user/models.py
from django.contrib.auth.models import User
from django.db import models

from custom_admin.models import Product


# Create your models here.


class ShoppingCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=50, null=True)
    total_price = models.FloatField(null=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True)

    def to_dict(self):
        return {
            "id": self.id,
            "status": self.id,
            "total_price": self.total_price,
            "create_data": self.create_date,
            "user": self.user.to_dict()
        }


class CartItem(models.Model):
    cart = models.ForeignKey(ShoppingCart, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(null=True)
    price = models.FloatField(null=True)
    total_price = models.FloatField(null=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True)

    def to_dict(self):
        return {
            "id": self.id,
            "quantity": self.quantity,
            "price": self.quantity,
            "total_price": self.total_price,
            "create_date": self.create_date,
            "product": self.product.to_dict(),
            "cart": self.cart.to_dict()
        }

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import forms, EmailField


class CustomUserCreationForm(UserCreationForm):
    email = EmailField()
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields

user/views.py
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect

from custom_admin.models import Product, Category
from user import authentication
from user.forms import CustomUserCreationForm
from user.models import ShoppingCart, CartItem


# Create your views here.


def index(request):
    categories = Category.objects.all()
    data = {
        "items": [],
        "categories": categories
    }
    for category in categories:
        data['items'].append({
            "category_id": category.id,
            "category_name": category.name,
            "products": Product.objects.filter(category_id=category)
        })
    return render(request, 'index.html', data)


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)
            auth_login(request, user)

            return redirect('user:index')
        else:
            messages.error(request, f"{form.error_messages}")
    else:
        form = CustomUserCreationForm()

    return render(request, 'authentication/register.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                # Redirect to a success page or home page
                return redirect('user:index')  # Replace 'home' with the URL name of your home page
        else:
            messages.error(request, f"{form.error_messages}")
    else:
        form = AuthenticationForm()

    return render(request, 'authentication/login.html', {'form': form})


def logout(request):
    auth_logout(request)
    return redirect('/')


def get_list_product(request):
    '''
        TODO:
            return list bao gồm tất cả các product
    '''
    products = Product.objects.all()
    get_list_product = [product.to_dict() for product in products]
    return JsonResponse(get_list_product, status=200, safe=False)


def get_list_category(request):
    products = Product.objects.all()
    get_list_category = []
    for product in products:
        get_list_category.append(product.to_dict())

    get_list_category = [product.to_dict() for product in products]
    return JsonResponse(get_list_category, status=200)


def get_page_product(request, page=1, size=10):
    '''
        TODO:
            return trang tất cả product nhưng bao gồm phân trang
            product.html

    '''
    products = Product.objects.all()
    paginator = Paginator(products, size)
    page_obj = paginator.get_page(page)
    response_data = {
        "total_elements": paginator.count,
        "total_pages": paginator.num_pages,
        "current_page": page,
        "content": [product.to_dict() for product in page_obj.object_list]
    }
    return JsonResponse(response_data, status=200)


def get_page_category(request, page=2, size=10):
    categorys = Category.objects.all()
    paginator = Paginator(categorys, size)
    page_obj = paginator.get_page(page)
    response_data = {
        "total_elements": paginator.count,
        "total_pages": paginator.num_pages,
        "current_page": page,
        "content": [category.to_dict() for category in page_obj.object_list]
    }
    return JsonResponse(response_data, status=200)


def get_product(request, product_id):
    '''
        TODO:
            return product với product_id tương ứng
    '''


@authentication()
def add_cart_item(request, product_id):
    '''
        TODO:
            Validate product_id tồn tại
            Tạo Cart Item với quantity default = 1
            Lưu Cart Item
     '''
    product = add_cart_item(Product, id=product_id)
    user_cart, created = ShoppingCart.objects.get_or_create(user=request.user)

    # Check if the product is already in the cart
    if product in user_cart.products.all():
        # Update quantity or perform any other action
        pass
    else:
        # Add the product to the cart
        user_cart.products.add(product)


def update_cart_item(request, product_id):
    '''
        TODO:
            Validate product_id tồn tại
            Cập nhật quantity product
            Nếu quantity <= 0 => Xóa khỏi database
    '''
    product = update_cart_item(Product, id=product_id)
    user_cart, created = ShoppingCart.objects.get_or_create(user=request.user)

    # Check if the product is in the cart
    if product in user_cart.products.all():
        # Perform the update logic based on your requirements
        # For example, updating quantity or removing the item
        # For simplicity, let's assume you want to double the quantity
        cart_item = user_cart.cart_items.get(product=product)
        cart_item.quantity *= 2
        cart_item.save()


def remove_from_cart(request, cart_item_id, cart_id):
    '''
        TODO:
            Validate cart_item_id, cart_id tồn tại
            Xóa cart_it em khỏi database
    '''
    user_cart = remove_from_cart(ShoppingCart, id=cart_item_id, user=request.user)
    cart_item = remove_from_cart(CartItem, id=cart_item_id, cart=user_cart)

    # Remove the item from the cart
    cart_item.delete()


def create_order(request):
    '''
        TODO:
        * Làm sau *
            Tạo Order từ user_id, address
            Lấy order_id
            Tạo các OrderItem với order_id và product_list
            Tính total_price của Order
            Cập nhật total_price của Order
    '''


def get_order_detail(request, order_id):
    '''
        TODO:
            Trả về thông tin order, và list order item
    '''


def error(request):
    code = request.GET.get('code', 500)
    message = request.GET.get('message', "Something went wrong")
    return render(request, 'error.html', {"code": code, "message": message})

user/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Eflyer</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif"/>
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet"
          href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
    <!-- fonts -->
    <link href="{% static 'https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap' %}" rel="stylesheet">
    <!-- font awesome -->
    <link rel="stylesheet" type="text/css"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--  -->
    <!-- owl stylesheets -->
    <link href="{% static 'https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext' %}"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesoeet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}"
          media="screen">
</head>
<body>
<!-- banner bg main start -->
<div class="banner_bg_main">
    <!-- header top section start -->
    <div class="container">
        <div class="header_section_top">
            <div class="row">
                <div class="col-sm-12">
                    <div class="custom_menu">
                        <ul>
                            <li><a href="#">Best Sellers</a></li>
                            <li><a href="#">Gift Ideas</a></li>
                            <li><a href="#">New Releases</a></li>
                            <li><a href="#">Today's Deals</a></li>
                            <li><a href="#">Customer Service</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- header top section start -->
    <!-- logo section start -->
    <div class="logo_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="logo"><a href="index.html"><img src="{% static 'images/logo.png' %}"></a></div>
                </div>
            </div>
        </div>
    </div>
    <!-- logo section end -->
    <!-- header section start -->
    <div class="header_section">
        <div class="container">
            <div class="containt_main">
                <div id="mySidenav" class="sidenav">
                    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                    <a href="/">Home</a>
                    <a href="fashion.html">Fashion</a>
                    <a href="electronic.html">Electronic</a>
                    <a href="{% url 'user:logout' %}">Logout</a>
                </div>
                <span class="toggle_icon" onclick="openNav()"><img src="{% static 'images/toggle-icon.png' %}"></span>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All Category
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        {% for category in categories %}
                        <a class="dropdown-item" href="#">{{category.name}}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="main">
                    <!-- Another variation with a button -->
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search this blog">
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="button"
                                    style="background-color: #f26522; border-color:#f26522 ">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="header_box">
                    <div class="lang_box ">
                        <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
                            <img src="{% static 'images/flag-uk.png' %}" alt="flag" class="mr-2 "
                                 title="United Kingdom"> English <i class="fa fa-angle-down ml-2"
                                                                    aria-hidden="true"></i>
                        </a>
                        <div class="dropdown-menu ">
                            <a href="#" class="dropdown-item">
                                <img src="{% static 'images/flag-france.png' %}" class="mr-2" alt="flag">
                                French
                            </a>
                        </div>
                    </div>
                    <div class="login_menu">
                        <ul>
                            {% if user.is_authenticated %}
                            <li><a href="#">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                <span class="padding_10">Cart</span></a>
                            </li>
                            <li><a href="#">
                                <i class="fa fa-user" aria-hidden="true"></i>
                                <span class="padding_10">User</span></a>
                            </li>
                            {% else %}
                            <li><a href="{% url 'user:login' %}">
                                <span class="padding_10">Login</span></a>
                            </li>
                            <li><a href="{% url 'user:register' %}">
                                <span class="padding_10">Register</span></a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}

    <!-- footer section start -->
    <div class="footer_section layout_padding">
        <div class="container">
            <div class="footer_logo"><a href="index.html"><img src="images/footer-logo.png"></a></div>
            <div class="input_bt">
                <input type="text" class="mail_bt" placeholder="Your Email" name="Your Email">
                <span class="subscribe_bt" id="basic-addon2"><a href="#">Subscribe</a></span>
            </div>
            <div class="footer_menu">
                <ul>
                    <li><a href="#">Best Sellers</a></li>
                    <li><a href="#">Gift Ideas</a></li>
                    <li><a href="#">New Releases</a></li>
                    <li><a href="#">Today's Deals</a></li>
                    <li><a href="#">Customer Service</a></li>
                </ul>
            </div>
            <div class="location_main">Help Line Number : <a href="#">+1 1800 1200 1200</a></div>
        </div>
    </div>
    <!-- footer section end -->
    <!-- copyright section start -->
    <div class="copyright_section">
        <div class="container">
            <p class="copyright_text">© 2020 All Rights Reserved. Design by <a href="https://html.design">Free html
                Templates</a></p>
        </div>
    </div>
    <!-- copyright section end -->
    <!-- Javascript files-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'js/plugin.js' %}"></script>
    <!-- sidebar -->
    <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>
</div>
</body>
</html>

user/templates/electronic.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- banner section start -->
<div class="banner_section layout_padding">
   <div class="container">
      <div id="my_slider" class="carousel slide" data-ride="carousel">
         <div class="carousel-inner">
            <div class="carousel-item active">
               <div class="row">
                  <div class="col-sm-12">
                     <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                     <div class="buynow_bt"><a href="#">Buy Now</a></div>
                  </div>
               </div>
            </div>
            <div class="carousel-item">
               <div class="row">
                  <div class="col-sm-12">
                     <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                     <div class="buynow_bt"><a href="#">Buy Now</a></div>
                  </div>
               </div>
            </div>
            <div class="carousel-item">
               <div class="row">
                  <div class="col-sm-12">
                     <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                     <div class="buynow_bt"><a href="#">Buy Now</a></div>
                  </div>
               </div>
            </div>
         </div>
         <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
         </a>
         <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
         </a>
      </div>
   </div>
</div>
<!-- banner section end -->
</div>
<!-- banner bg main end -->
<!-- electronic section start -->
<div class="fashion_section">
   <div id="electronic_main_slider" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
         <div class="carousel-item active">
            <div class="container">
               <h1 class="fashion_taital">Electronic</h1>
               <div class="fashion_section_2">
                  <div class="row">
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">Laptop</h4>
                           <p class="price_text">Start Price <span style="color: #262626;">$ 100</span></p>
                           <div class="electronic_img"><img src="images/laptop-img.png"></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">Mobile</h4>
                           <p class="price_text">Start Price <span style="color: #262626;">$ 100</span></p>
                           <div class="electronic_img"><img src="images/mobile-img.png"></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">Computers</h4>
                           <p class="price_text">Start Price <span style="color: #262626;">$ 100</span></p>
                           <div class="electronic_img"><img src="images/computer-img.png"></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="carousel-item">
            <div class="container">
               <h1 class="fashion_taital">Electronic</h1>
               <div class="fashion_section_2">
                  <div class="row">
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">Laptop</h4>
                           <p class="price_text">Start Price <span style="color: #262626;">$ 100</span></p>
                           <div class="electronic_img"><img src="images/laptop-img.png"></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">Mobile</h4>
                           <p class="price_text">Start Price <span style="color: #262626;">$ 100</span></p>
                           <div class="electronic_img"><img src="images/mobile-img.png"></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">Computers</h4>
                           <p class="price_text">Start Price <span style="color: #262626;">$ 100</span></p>
                           <div class="electronic_img"><img src="images/computer-img.png"></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="carousel-item">
            <div class="container">
               <h1 class="fashion_taital">Electronic</h1>
               <div class="fashion_section_2">
                  <div class="row">
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">Laptop</h4>
                           <p class="price_text">Start Price <span style="color: #262626;">$ 100</span></p>
                           <div class="electronic_img"><img src="images/laptop-img.png"></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">Mobile</h4>
                           <p class="price_text">Start Price <span style="color: #262626;">$ 100</span></p>
                           <div class="electronic_img"><img src="images/mobile-img.png"></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">Computers</h4>
                           <p class="price_text">Start Price <span style="color: #262626;">$ 100</span></p>
                           <div class="electronic_img"><img src="images/computer-img.png"></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <a class="carousel-control-prev" href="#electronic_main_slider" role="button" data-slide="prev">
         <i class="fa fa-angle-left"></i>
      </a>
      <a class="carousel-control-next" href="#electronic_main_slider" role="button" data-slide="next">
         <i class="fa fa-angle-right"></i>
      </a>
   </div>
</div>
<!-- electronic section end -->
{% endblock %}

user/templates/error.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Corona Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
          <div class="row flex-grow">
            <div class="col-lg-7 mx-auto text-white">
              <div class="row align-items-center d-flex flex-row">
                <div class="col-lg-6 text-lg-right pr-lg-4">
                  <h1 class="display-1 mb-0">{{code}}</h1>
                </div>
                <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                  <h2>SORRY!</h2>
                  <h3 class="font-weight-light">{{message}}</h3>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 text-center mt-xl-2">
                  <a class="text-white font-weight-medium" href="/">Back to home</a>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 mt-xl-2">
                  <p class="text-white font-weight-medium text-center">Copyright &copy; 2020 All rights reserved.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
    <!-- endinject -->
  </body>
</html>