Amogus2009/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('custom_admin/', include('custom_admin.urls')),
    path("", include("user.urls")),
]

custom_admin/urls.py
from django.urls import path
from . import views

app_name = "custom_admin"
urlpatterns = [
    path("", views.admin_dashboard, name='admin_dashboard'),
    path("product/page/", views.get_page_product, name='admin_page_product'),
    path("category/page/", views.get_page_category, name='admin_page_category'),

    path("logout/", views.logout, name='logout'),

]

user/urls.py
from django.urls import path
from . import views
from .views import register, login

app_name = "user"
urlpatterns = [
    path("", views.index, name='index'),
    path("product/list/", views.get_list_product, name='product_list'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path("logout/", views.logout, name='logout'),
    path("error/", views.error, name='error')
]

custom_admin/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, null=True)
    description = models.TextField(null=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True)

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "create_date": self.create_date
        }


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    description = models.TextField(null=True)
    price = models.FloatField(null=True)
    quantity_available = models.PositiveIntegerField(null=True)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True)
    imgUrl = models.ImageField(
        upload_to='blog/static/assets/img', blank=True, default='post-landscape-1.jpg')

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "price": self.price,
            "quantity_available": self.quantity_available,
            "category": self.category_id.to_dict(),
            "create_date": self.create_date,
            "imgUrl": self.imgUrl.url if self.imgUrl else ''
        }


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True)
    total_price = models.FloatField(null=True)
    status = models.CharField(max_length=50, null=True)
    shipping_address = models.TextField(null=True)

    def update_total_price(self, new_price):
        self.total_price = new_price


    def to_dict(self):
        return {
            "id": self.id,
            "shipping_address": self.shipping_address,
            "status": self.status,
            "total_price": self.total_price,
            "create_date": self.create_date,
            "user": self.user.to_dict()
        }


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(null=True)
    price = models.FloatField(null=True)
    total_price = models.FloatField(null=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True)

    def to_dict(self):
        return {
            "id": self.id,
            "quantity": self.quantity,
            "price": self.price,
            "total_price": self.total_price,
            "create_date": self.create_date,
            "product": self.product.to_dict(),
            "order": self.order.to_dict()
        }

custom_admin/views.py
import json

from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpResponseBadRequest, JsonResponse, HttpResponseNotAllowed, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth import logout as auth_logout

from custom_admin import authentication
from custom_admin.models import Product, Category, Order


@authentication()
def admin_dashboard(request):
    '''
    TODO:
        Render the custom_admin dashboard with relevant statistics and information
    '''
    total_products = Product.objects.count()
    total_orders = Order.objects.count()

    # Add more statistics or information as needed

    return render(request, 'admin_index.html', {'total_products': total_products, 'total_orders': total_orders})


def logout(request):
    auth_logout(request)
    return redirect('/')


def get_list_product(request):
    '''
        TODO:
            return list bao gồm tất cả các product
    '''
    products = Product.objects.all()
    get_list_product = [product.to_dict() for product in products]
    return JsonResponse(get_list_product, status=200, safe=False)


def get_list_category(request):
    products = Product.objects.all()
    get_list_category = []
    for product in products:
        get_list_category.append(product.to_dict())

    get_list_category = [product.to_dict() for product in products]
    return JsonResponse(get_list_category, status=200)


def get_page_product(request):
    '''
        TODO:
            return trang tất cả product nhưng bao gồm phân trang
            product.html
    '''
    page = request.GET.get('page', 1)
    size = request.GET.get('size', 50)

    # Convert page and size to integers
    page = int(page)
    size = int(size)
    products = Product.objects.all()
    paginator = Paginator(products, size)
    page_obj = paginator.get_page(page)
    response_data = {
        "total_elements": paginator.count,
        "total_pages": paginator.num_pages,
        "current_page": page,
        "content": [product.to_dict() for product in page_obj.object_list]
    }
    return render(request, 'products/list.html', context=response_data)


def get_page_category(request):
    page = request.GET.get('page', 1)
    size = request.GET.get('size', 50)

    # Convert page and size to integers
    page = int(page)
    size = int(size)
    categorys = Category.objects.all()
    paginator = Paginator(categorys, size)
    page_obj = paginator.get_page(page)
    response_data = {
        "total_elements": paginator.count,
        "total_pages": paginator.num_pages,
        "current_page": page,
        "content": [category.to_dict() for category in page_obj.object_list]
    }
    return render(request, 'categories/list.html', context=response_data)


def get_page_user(request):
    page = request.GET.get('page', 1)
    size = request.GET.get('size', 50)

    # Convert page and size to integers
    page = int(page)
    size = int(size)
    users = User.objects.all()
    paginator = Paginator(users, size)
    page_obj = paginator.get_page(page)
    users_dict = []
    for user in page_obj.object_list:
        users_dict.append({
            "id": user.id,
            "username": user.username,
            "email": user.email,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "role": "ADMIN" if user.is_superuser else "USER",
            "date_joined": user.date_joined
        })
    response_data = {
        "total_elements": paginator.count,
        "total_pages": paginator.num_pages,
        "current_page": page,
        "content": users_dict
    }
    return render(request, 'users/list.html', context=response_data)


@csrf_exempt
@authentication()
def create_user(request):
    '''
    TODO:
        method: GET
            Render the Add User page with the form
        method: POST
            Validate the information in the form
            Add a new user to the database and redirect to the page with all users
    '''


@csrf_exempt
@authentication()
def create_product(request):
    '''
    TODO:
        method: GET
            Render the Add Product page with the form
        method: POST
            Validate the information in the form
            Add a new product to the database and redirect to the page with all products
    '''
    if request.method == "POST":
        # For file uploads, use request.FILES for the image field
        name = request.POST.get("name")
        description = request.POST.get("description")
        try:
            quantity = int(request.POST.get("quantity"))
            price = float(request.POST.get("price"))
        except TypeError as error:
            return JsonResponse({"error": "bro, it must be a number"}, status=400)

        category_id = request.POST.get("category_id")
        category = get_object_or_404(Category, id=category_id)

        # Handle file upload separately from other form fields
        image = request.FILES.get("img", None)

        product = Product(name=name, description=description, quantity_available=quantity, price=price,
                          category_id=category,
                          imgUrl=image)
        product.save()

        # return redirect('custom_admin:admin_page_product')
        return JsonResponse({"status": "success", "data": product.to_dict()})
    elif request.method == "GET":
        categories = Category.objects.all()
        return render(request, 'products/add.html', {"categories": categories})
    else:
        return JsonResponse({"error": "Method not allowed"}, status=405)


@csrf_exempt
def create_category(request):
    if request.method == "POST":
        request_data = json.loads(request.body.decode('utf-8'))
        name = request_data.get("name")
        description = request_data.get("description")

        category = Category(name=name, description=description)
        category.save()
        return JsonResponse(status=200, data=category.to_dict(), safe=False)

    elif request.method == "GET":
        return render(request, 'categories/add.html')
    else:
        return HttpResponseNotAllowed('menthod not  allow')


@authentication()
def edit_product(request, product_id):
    '''
    TODO:
        method: GET
            Render the Update Product page with the form
        method: POST
            Validate the information in the form
            Update the product information in the database and redirect to the page with all products
    '''
    product = get_object_or_404(Product, id=product_id)
    if request.method == "POST":
        name = request.POST.get("name")
        description = request.POST.get("description")
        try:
            quantity = int(request.POST.get("quantity"))
            price = float(request.POST.get("price"))
        except TypeError as error:
            return JsonResponse({"error": "bro, it must be a number"}, status=400)

        category_id = request.POST.get("category_id")
        category = get_object_or_404(Category, id=category_id)

        # Handle file upload separately from other form fields
        image = request.FILES.get("img", None)

        product.name = name
        product.description = description
        product.quantity_available = quantity
        product.price = price
        product.category_id = category
        product.imgUrl = image
        product.save()
        # return redirect('custom_admin:admin_page_product')
        return JsonResponse({"status": "success", "data": product.to_dict()})
    elif request.method == "GET":
        categories = Category.objects.all()
        return render(request, 'products/edit.html', {"product": product, "categories": categories})
    elif request.method == "DELETE":
        # Delete the product
        product.delete()
        return HttpResponse("Product deleted successfully")
    else:
        return HttpResponseNotAllowed("Method Not Allowed")


@authentication()
def edit_user(request, user_id):
    '''
    TODO:
        method: GET
            Render the Update User page with the form
        method: POST
            Validate the information in the form
            Update the user information in the database and redirect to the page with all users
    '''


@authentication()
def order_list(request):
    '''
    TODO:
        Render a page with a list of all orders for custom_admin
    '''
    orders = Order.objects.all()

    return render(request, 'order_list.html', {'orders': orders})


@authentication()
def order_detail(request, order_id):
    '''
    TODO:
        Render a page with details of a specific order
    '''
    order = get_object_or_404(Order, id=order_id)

    return render(request, 'order_detail.html', {'order': order})


@authentication()
def update_order_status(request, order_id):
    '''
    TODO:
        method: GET
            Render the Update Order Status page with the form
        method: POST
            Validate the information in the form
            Update the order status in the database and redirect to the page with all orders
    '''
    pass


@authentication()
def edit_order(request, order_id):
    '''
    TODO:
        method: GET
            Render the Update Category page with the form
        method: POST
            Validate the information in the form
            Update the category information in the database and redirect to the page with all categories
    '''
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        form = Order(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('all_orders')  # Redirect to the page with all orders
    else:
        form = Order(instance=order)

    return render(request, 'update_order_status.html', {'form': form, 'order': order})


def edit_category(request):
    return None

custom_admin/templates/partials/_footer.html
{% load static %}
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span>
  </div>
</footer>

custom_admin/templates/partials/_navbar.html
{% load static %}
<nav class="navbar p-0 fixed-top d-flex flex-row">
  <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
    <a class="navbar-brand brand-logo-mini" href="/custom_admin/"><img src="{% static 'assets/images/logo-mini.png' %}" alt="logo" /></a>
  </div>
  <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="mdi mdi-menu"></span>
    </button>
    <ul class="navbar-nav w-100">
      <li class="nav-item w-100">
        <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
          <input type="text" class="form-control" placeholder="Search products">
        </form>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
<!--      <li class="nav-item dropdown d-none d-lg-block">-->
<!--        <a class="nav-link btn btn-success create-new-button" id="createbuttonDropdown" data-toggle="dropdown" aria-expanded="false" href="#">+ Create New Project</a>-->
<!--        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="createbuttonDropdown">-->
<!--          <h6 class="p-3 mb-0">Projects</h6>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item preview-item">-->
<!--            <div class="preview-thumbnail">-->
<!--              <div class="preview-icon bg-dark rounded-circle">-->
<!--                <i class="mdi mdi-file-outline text-primary"></i>-->
<!--              </div>-->
<!--            </div>-->
<!--            <div class="preview-item-content">-->
<!--              <p class="preview-subject ellipsis mb-1">Software Development</p>-->
<!--            </div>-->
<!--          </a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item preview-item">-->
<!--            <div class="preview-thumbnail">-->
<!--              <div class="preview-icon bg-dark rounded-circle">-->
<!--                <i class="mdi mdi-web text-info"></i>-->
<!--              </div>-->
<!--            </div>-->
<!--            <div class="preview-item-content">-->
<!--              <p class="preview-subject ellipsis mb-1">UI Development</p>-->
<!--            </div>-->
<!--          </a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item preview-item">-->
<!--            <div class="preview-thumbnail">-->
<!--              <div class="preview-icon bg-dark rounded-circle">-->
<!--                <i class="mdi mdi-layers text-danger"></i>-->
<!--              </div>-->
<!--            </div>-->
<!--            <div class="preview-item-content">-->
<!--              <p class="preview-subject ellipsis mb-1">Software Testing</p>-->
<!--            </div>-->
<!--          </a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <p class="p-3 mb-0 text-center">See all projects</p>-->
<!--        </div>-->
<!--      </li>-->
<!--      <li class="nav-item nav-settings d-none d-lg-block">-->
<!--        <a class="nav-link" href="#">-->
<!--          <i class="mdi mdi-view-grid"></i>-->
<!--        </a>-->
<!--      </li>-->
      <li class="nav-item dropdown border-left">
        <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
          <i class="mdi mdi-email"></i>
          <span class="count bg-success"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
          <h6 class="p-3 mb-0">Messages</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="{% static 'assets/images/faces/face4.jpg' %}" alt="image" class="rounded-circle profile-pic">
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1">Mark send you a message</p>
              <p class="text-muted mb-0"> 1 Minutes ago </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="{% static 'assets/images/faces/face2.jpg' %}" alt="image" class="rounded-circle profile-pic">
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1">Cregh send you a message</p>
              <p class="text-muted mb-0"> 15 Minutes ago </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="{% static 'assets/images/faces/face3.jpg' %}" alt="image" class="rounded-circle profile-pic">
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1">Profile picture updated</p>
              <p class="text-muted mb-0"> 18 Minutes ago </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <p class="p-3 mb-0 text-center">4 new messages</p>
        </div>
      </li>
      <li class="nav-item dropdown border-left">
        <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
          <i class="mdi mdi-bell"></i>
          <span class="count bg-danger"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
          <h6 class="p-3 mb-0">Notifications</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-calendar text-success"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Event today</p>
              <p class="text-muted ellipsis mb-0"> Just a reminder that you have an event today </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-settings text-danger"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Settings</p>
              <p class="text-muted ellipsis mb-0"> Update dashboard </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-link-variant text-warning"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Launch Admin</p>
              <p class="text-muted ellipsis mb-0"> New admin wow! </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <p class="p-3 mb-0 text-center">See all notifications</p>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
          <div class="navbar-profile">
            <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face16.jpg' %}" alt="">
            <p class="mb-0 d-none d-sm-block navbar-profile-name">Admin</p>
            <i class="mdi mdi-menu-down d-none d-sm-block"></i>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
          <h6 class="p-3 mb-0">Profile</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-settings text-success"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Settings</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-logout text-danger"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Log out</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <p class="p-3 mb-0 text-center">Advanced settings</p>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="mdi mdi-format-line-spacing"></span>
    </button>
  </div>
</nav>

custom_admin/templates/partials/_sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
    <a class="sidebar-brand brand-logo" href="/custom_admin"><img src="{% static 'assets/images/logo.png' %}" alt="logo" /></a>
    <a class="sidebar-brand brand-logo-mini" href="/custom_admin"><img src="{% static 'assets/images/logo-mini.png' %}" alt="logo" /></a>
  </div>
  <ul class="nav">
    <li class="nav-item profile">
      <div class="profile-desc">
        <div class="profile-pic">
          <div class="count-indicator">
            <img class="img-xs rounded-circle " src="{% static 'assets/images/faces/face16.jpg' %}" alt="">
            <span class="count bg-success"></span>
          </div>
          <div class="profile-name">
            <h5 class="mb-0 font-weight-normal">Admin</h5>
            <span>System Admin</span>
          </div>
        </div>
        <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
        <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
          <a href="#" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-settings text-primary"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1 text-small">Account settings</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-onepassword  text-info"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-calendar-today text-success"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1 text-small">To-do list</p>
            </div>
          </a>
        </div>
      </div>
    </li>
    <li class="nav-item nav-category">
      <span class="nav-link">Navigation</span>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" href="/custom_admin/">
        <span class="menu-icon">
          <i class="mdi mdi-speedometer"></i>
        </span>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" data-toggle="collapse" href="#product" aria-expanded="false" aria-controls="product">
        <span class="menu-icon">
          <i class="mdi mdi-widgets"></i>
        </span>
        <span class="menu-title">Products</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="product">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{% url 'custom_admin:admin_page_product' %}">View All</a></li>
          <li class="nav-item"> <a class="nav-link" href="#">Add New</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" data-toggle="collapse" href="#category" aria-expanded="false" aria-controls="category">
        <span class="menu-icon">
          <i class="mdi mdi-grid"></i>
        </span>
        <span class="menu-title">Categories</span>
      <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="category">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{% url 'custom_admin:admin_page_category' %}">View All</a></li>
          <li class="nav-item"> <a class="nav-link" href="#">Add New</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" href="#">
        <span class="menu-icon">
          <i class="mdi mdi-clipboard-text"></i>
        </span>
        <span class="menu-title">Orders</span>
      </a>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" data-toggle="collapse" href="#user" aria-expanded="false" aria-controls="user">
        <span class="menu-icon">
          <i class="mdi mdi-contacts"></i>
        </span>
        <span class="menu-title">Users</span>
      <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="user">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="#">View All</a></li>
          <li class="nav-item"> <a class="nav-link" href="#">Add New</a></li>
        </ul>
      </div>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" href="#">
        <span class="menu-icon">
          <i class="mdi mdi-chart-bar"></i>
        </span>
        <span class="menu-title">Analytics</span>
      </a>
    </li>
<!--    <li class="nav-item menu-items">-->
<!--      <a class="nav-link" href="pages/tables/basic-table.html">-->
<!--        <span class="menu-icon">-->
<!--          <i class="mdi mdi-table-large"></i>-->
<!--        </span>-->
<!--        <span class="menu-title">Tables</span>-->
<!--      </a>-->
<!--    </li>-->
<!--    <li class="nav-item menu-items">-->
<!--      <a class="nav-link" href="pages/icons/mdi.html">-->
<!--        <span class="menu-icon">-->
<!--          <i class="mdi mdi-contacts"></i>-->
<!--        </span>-->
<!--        <span class="menu-title">Icons</span>-->
<!--      </a>-->
<!--    </li>-->
<!--    <li class="nav-item menu-items">-->
<!--      <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">-->
<!--        <span class="menu-icon">-->
<!--          <i class="mdi mdi-security"></i>-->
<!--        </span>-->
<!--        <span class="menu-title">User Pages</span>-->
<!--        <i class="menu-arrow"></i>-->
<!--      </a>-->
<!--      <div class="collapse" id="auth">-->
<!--        <ul class="nav flex-column sub-menu">-->
<!--          <li class="nav-item"> <a class="nav-link" href="pages/samples/blank-page.html"> Blank Page </a></li>-->
<!--          <li class="nav-item"> <a class="nav-link" href="pages/samples/error-404.html"> 404 </a></li>-->
<!--          <li class="nav-item"> <a class="nav-link" href="pages/samples/error-500.html"> 500 </a></li>-->
<!--          <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html"> Login </a></li>-->
<!--          <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>-->
<!--        </ul>-->
<!--      </div>-->
<!--    </li>-->
<!--    <li class="nav-item menu-items">-->
<!--      <a class="nav-link" href="documentation">-->
<!--        <span class="menu-icon">-->
<!--          <i class="mdi mdi-file-document-box"></i>-->
<!--        </span>-->
<!--        <span class="menu-title">Documentation</span>-->
<!--      </a>-->
<!--    </li>-->
  </ul>
</nav>